import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const Layout: React.FC = ({ children }) => {
    const [searchText, setSearchText] = useState("");
    const router = useRouter();

    return (
        <div className="bg-gradient-to-bl from-green-300 to-blue-800">
            <div className="container mx-auto flex flex-col">
                <Head>
                    <title>Art Explorer</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="self-center">
                    <Link href="/">
                        <a>
                            <h1 className="text-5xl font-bold mt-14 transition hover:scale-105">
                                Art Explorer
                            </h1>
                        </a>
                    </Link>
                </div>
                <form
                    className="self-center my-5"
                    onSubmit={(e) => {
                        e.preventDefault();
                        if (searchText.length > 0) {
                            router.push({
                                pathname: "/search",
                                query: { searchTerm: searchText },
                            });
                        }
                    }}
                >
                    <input
                        className="shadow-md p-2 rounded-lg mx-4 focus:outline-none focus:ring focus:ring-blue-600"
                        value={searchText}
                        onChange={(e) => setSearchText(e.target.value)}
                        placeholder="Enter search"
                    />
                    <button
                        className="bg-gradient-to-r from-blue-600 to-blue-500 p-2 rounded-lg shadow-md text-white hover:bg-gradient-to-r hover:from-blue-700 hover:to-blue-600"
                        type="submit"
                    >
                        Search
                    </button>
                </form>
                {children}
            </div>
        </div>
    );
};

export default Layout;
